development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:a8a5047d5ec2527be49426a650c4cf9a@pike.redistogo.com:10841/
  channel_prefix: rate_my_professor_production
